cache = true
max_cache_age = "2d"
max_retries = 3
retry_wait_time = 2
timeout = 20
scheme = ["https", "http"]
accept = [200, 204, 206, 403, 429]
exclude_loopback = true
include_mail = false
exclude_path = ["node_modules", "dist/pagefind", "LICENSES"]
exclude = ['^https://example\.stanford\.edu(?:/|$)']
